version: "3.1"

services:
  postgres:
    container_name: postgres
    image: postgres:13
    restart: "on-failure"
    ports:
      - 5432:5432
    volumes:
      - ./postgredb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8

  redis:
    container_name: redis
    image: redis
    restart: "on-failure"
    ports:
      - 6369:6369
