# Generated by Django 4.0.5 on 2022-07-02 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_alter_file_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileaccess',
            options={'verbose_name': 'File Access', 'verbose_name_plural': 'File Access'},
        ),
    ]
