# Generated by Django 4.0.5 on 2022-07-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
