# Generated by Django 4.0.5 on 2022-07-02 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
    ]
